id: QmRit3mZ9Ah1LeTR1HQmGsByXX4RJkrfz87GeUwfP72t5u
description: Returns hello world
tags: []
source: .
trigger:
    type: https
    method: GET
    paths:
        - /ping
domains:
    - global
execution:
    timeout: 10s
    memory: 10MB
    call: helloworld
